export const GET_LEADS = "GET_LEADS"
export const DELETE_LEAD = "DELETE_LEAD"
export const ADD_LEAD = "ADD_LEAD"

export const GET_ERRORS = "GET_ERRORS"
export const CREATE_MESSAGE = "CREATE_MESSAGE"

export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const GET_USER = "GET_USER"
export const LOGIN_USER = "LOGIN_USER"

export const USER_LOADING = "USER_LOADING"
export const USER_LOADED =  "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILED = "LOGOUT_FAILED"

export const GET_GROUPS = "GET_GROUPS"
export const CREATE_GROUP = "CREATE_GROUP"
export const CREATE_INIT_MEMBER = "CREATE_INIT_MEMBER"
export const GET_USERS_IN_GROUP = "GET_USERS_IN_GROUP"
export const UPDATE_GROUP_USER = "UPDATE_GROUP_USER"
export const UPDATE_GROUP = "UPDATE_GROUP"
export const INVITE_USER = "INVITE_USER"
export const ASSIGN_SS = "ASSIGN_SS"
export const PROMOTE_GROUP_USER = "PROMOTE_GROUP_USER"
export const REMOVE_GROUP_USER = "REMOVE_GROUP_USER"
export const LEAVE_GROUP = "LEAVE_GROUP"
export const DELETE_GROUP = "DELETE_GROUP"

