# Generated by Django 5.1.3 on 2024-12-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usersettings_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
    ]
