# Generated by Django 5.1.3 on 2024-11-22 22:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_price_min', models.IntegerField(default=0)),
                ('recommended_price_max', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SSGroupUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('gift_preferences', models.CharField(blank=True, max_length=500)),
                ('giftee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretsanta.ssgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ssgroup',
            name='members',
            field=models.ManyToManyField(through='secretsanta.SSGroupUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
