# Generated by Django 5.1.3 on 2024-11-23 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssgroup',
            name='members',
            field=models.ManyToManyField(blank=True, through='secretsanta.SSGroupUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
